### PR TITLE
Fix issue #6

### PR DESCRIPTION
**Pull request by plainerman**
Fix `eth_getFilterChanges` to only include new hashes.

### CODE REVIEW

**Comment by uldaman** [comment]
I did this before, but it will lead to a problem. When the client sends a transaction, it will probably be packaged very quickly, then when the client call `eth_getFilterChanges `,  it won't get the block just packed, so I include the current block in the method.

**Comment by plainerman** [comment]
Could you elaborate a bit on this issue and why your proposed code could fix this issue? Especially:
1. Does only the first block cause an issue? Because in the constructor you would only include the previous block before subscribing.
2. Why does subscribing to the filter before sending the transaction does not fix this problem?

**Comment by plainerman** [comment]
But why would this be an issue with vechain but not with ethereum? Are the vechain blocks so much faster?

**Comment by uldaman** [comment]
I am using vechain's `--on-demand` mode, it immediately packs after receiving a transaction. So if I send a transaction first, then subscribe, I will not get the result of the transaction. 

The correct way is to subscribe first, then send the transaction. But I can't assume that the user will do this. So every time I return to the current block (this is also wrong, I think it should be only the first time to return to the current block.).

**Comment by plainerman** [comment]
Including the first block will only delay the problem. If two blocks are mined nearly instantly (or network delays ...), the transaction won't be included either.

**Comment by uldaman** [comment]
Yes. So this is the `Truffle` own problem, when I run `truffle test`:

```
INFO - gear.rpc[line:178] - received rpc request - eth_sendTransaction
INFO - gear.rpc[line:229] - received rpc request - eth_newBlockFilter
INFO - gear.rpc[line:241] - received rpc request - eth_getFilterChanges
INFO - gear.rpc[line:201] - received rpc request - eth_getTransactionReceipt
INFO - gear.rpc[line:149] - received rpc request - eth_getCode
INFO - gear.rpc[line:235] - received rpc request - eth_uninstallFilter
```

Should be subscribed first...

I will think again about any better solution. If you have it, please let me know.

**Comment by plainerman** [comment]
We could store all transactions from `sendTransaction `and if a new blockfilter is created, we begin with the block that contained the transaction (if any). Then delete the stored transactions. 

This would ensure that:
1. Transactions are included
2. Send empty changes if subscribed without a sent transaction

**Comment by plainerman** [comment]
Just all transactions?

**Comment by plainerman** [comment]
Or we could map them by the id they send with? This sounds like a good idea.

**Comment by uldaman** [comment]
The problem is that `new blockfilter` does not have any additional information, so I can't know which block to begin with.

**Comment by plainerman** [comment]
Every application should send a unique id with every request. We could then map each `eth_sendTransaction `with the id. When a new blockfilter is requested with the same id we include the previous transaction-block matched by the id.

**Comment by uldaman** [comment]
If `sendTransactionand ` I `map [tx id => block num]`, then I may have the following mapping:

```
0x1111111: block num
0x222222:block num
...
```

So, when `newBlockFilter`, Which block num does it begin with?

**Comment by uldaman** [comment]
What you mean is to modify the interface like `eth_newBlockFilter(client_id)`?

**Comment by plainerman** [comment]
The web3-gear internal interface, yes. This would not change the user application nor the communication with thor.

**Comment by plainerman** [comment]
Changing `client.py.new_block_filter()` ->`client.py.new_block_filter(clientId)`. Because if you look at the [Ethereum RPC interface](https://github.com/ethereum/wiki/wiki/JSON-RPC), the id is already added.

**Comment by plainerman** [comment]
Look down to the examples listed under every command, there should always be a field "id" added. 

Estimate Gas for example:
```
// Request
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{see above}],"id":1}'

// Result
{
  "id":1,
  "jsonrpc": "2.0",
  "result": "0x5208" // 21000
}
```

**Comment by uldaman** [comment]
This `id` is not client id, it is to make the response consistent with the request. You can see [json-rpc-what-is-the-id-for](https://stackoverflow.com/questions/2210791/json-rpc-what-is-the-id-for).

**Comment by uldaman** [comment]
This id can't be obtained in the rpc method, it is used internally by json rpc.  

Within the rpc method, only `params` can be obtained, you can try it.

**Comment by plainerman** [comment]
I see the problem. I would say we implement the hack with the constructor including the previous block? Maybe with a flag to disable it?

**Comment by plainerman** [comment]
Or create an issue at truffle itself.

**Comment by uldaman** [comment]
But this not be an issue  with ethereum, because when ethereum receives a transaction, there will be pow, so the transaction will not be packaged immediately.

**Comment by uldaman** [comment]
I Think the current solution is to apply your changes first, but move block num forward one when constructing the BlockFilter.

**Pull request merged**
